spring:
  datasource:
    url: jdbc:h2:mem:financedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: root
    password: "Writer"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
